// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTodosParams creates a new GetTodosParams object
// no default values defined in spec.
func NewGetTodosParams() GetTodosParams {

	return GetTodosParams{}
}

// GetTodosParams contains all the bound params for the get todos operation
// typically these are obtained from a http.Request
//
// swagger:parameters getTodos
type GetTodosParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*tags to filter the search by
	  In: query
	*/
	Tags *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTodosParams() beforehand.
func (o *GetTodosParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qTags, qhkTags, _ := qs.GetOK("tags")
	if err := o.bindTags(qTags, qhkTags, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTags binds and validates parameter Tags from query.
func (o *GetTodosParams) bindTags(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Tags = &raw

	return nil
}
