// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/juliendoutre/go-api-benchmark/swagger/models"
)

// GetTodosHandlerFunc turns a function with the right signature into a get todos handler
type GetTodosHandlerFunc func(GetTodosParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTodosHandlerFunc) Handle(params GetTodosParams) middleware.Responder {
	return fn(params)
}

// GetTodosHandler interface for that can handle valid get todos params
type GetTodosHandler interface {
	Handle(GetTodosParams) middleware.Responder
}

// NewGetTodos creates a new http.Handler for the get todos operation
func NewGetTodos(ctx *middleware.Context, handler GetTodosHandler) *GetTodos {
	return &GetTodos{Context: ctx, Handler: handler}
}

/*GetTodos swagger:route GET /todos getTodos

Get stored todos

*/
type GetTodos struct {
	Context *middleware.Context
	Handler GetTodosHandler
}

func (o *GetTodos) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTodosParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetTodosOKBody get todos o k body
// swagger:model GetTodosOKBody
type GetTodosOKBody struct {

	// todos
	Todos []*models.Todo `json:"todos"`
}

// Validate validates this get todos o k body
func (o *GetTodosOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTodos(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTodosOKBody) validateTodos(formats strfmt.Registry) error {

	if swag.IsZero(o.Todos) { // not required
		return nil
	}

	for i := 0; i < len(o.Todos); i++ {
		if swag.IsZero(o.Todos[i]) { // not required
			continue
		}

		if o.Todos[i] != nil {
			if err := o.Todos[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getTodosOK" + "." + "todos" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTodosOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTodosOKBody) UnmarshalBinary(b []byte) error {
	var res GetTodosOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
